# builder
FROM node:20-bullseye AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY ../. .
RUN npm run build
# genera clientes prisma (por cada schema)
RUN npx prisma generate --schema=prisma/schemas/main.schema.prisma
RUN npx prisma migrate dev --name init --schema=prisma/schemas/main.schema.prisma
RUN npx prisma generate --schema=prisma/schemas/tenantA.schema.prisma
RUN npx prisma migrate dev --name init --schema=prisma/schemas/tenantA.schema.prisma
RUN npx prisma generate --schema=prisma/schemas/tenantB.schema.prisma
RUN npx prisma migrate dev --name init --schema=prisma/schemas/tenantB.schema.prisma

# runtime
FROM node:20-bullseye-slim
WORKDIR /app
ENV NODE_ENV=production
# sqlite runtime
RUN apt-get update && apt-get install -y sqlite3 libsqlite3-0 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
CMD ["node", "dist/main.js"]
