version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./:/app:cached
      - ./prisma/db:/app/prisma/db   # aquí persistes los .db fuera del contenedor
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL_MAIN: "file:./prisma/db/main.db"
      DATABASE_URL_TENANTA: "file:./prisma/db/tenantA.db"
    command: sh -c "npm run prisma:gen:main && npm run prisma:migrate:main && npm run build && node dist/main.js"
